version: "3.9"

services:

  postgres:
    image: postgres:16-alpine
    container_name: ochiga-postgres
    restart: always
    environment:
      POSTGRES_USER: ochiga
      POSTGRES_PASSWORD: ochiga123
      POSTGRES_DB: ochiga_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: ochiga-redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: ochiga-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ochiga
      DB_PASSWORD: ochiga123
      DB_NAME: ochiga_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APP_JWT_SECRET: supersecretjwtkey
      SUPABASE_JWT_SECRET: supersupabasejwtkey
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    container_name: ochiga-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
    depends_on:
      - backend

volumes:
  pgdata:
